import type { Product, Tender, Job, NewsArticle } from '@/lib/types';

const products: Product[] = [
  // Finished Products
  {
    id: 'prod-01',
    name: 'Fibre Garden Article Pot',
    productType: 'product',
    category: 'Garden Articles',
    image: { id: '/products/fibre-garden-article-pot-kscmmc.webp' },
    shortDescription: 'Eco-friendly coir pots for gardening.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'prod-02',
    name: 'Coconut Pith Block',
    productType: 'product',
    category: 'Garden Articles',
    image: { id: '/products/coconut-pith-block-weight-2kg-kscmmc.webp' },
    shortDescription: 'Compressed coconut pith for soil conditioning.',
    specifications: [],
    brochureUrl: '#',
  },

  // Machines
  {
    id: 'mach-01',
    name: 'Automatic Spinning Machine',
    productType: 'machine',
    category: 'Spinning',
    image: { id: '/machinery/automatic-spinning-machine-double-combing-asm.webp' },
    shortDescription: 'High-speed automatic spinning machine for coir yarn.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-02',
    name: 'Automatic Spinning Machine With Autofeeder',
    productType: 'machine',
    category: 'Spinning',
    image: { id: '/machinery/automatic-spinning-machine-with-autofeeder-asm.webp' },
    shortDescription: 'Automatic spinning machine equipped with an auto-feeder mechanism.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-03',
    name: '65 HP Integrated Defibering Machine',
    productType: 'machine',
    category: 'Defibering',
    image: { id: '/machinery/65hp-integrated-defibering-machine.webp' },
    shortDescription: 'Powerful 65 HP machine for integrated defibering processes.',
    specifications: [{ key: 'Power', value: '65 HP' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-04',
    name: 'Dehusking Machine',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/deshusking-machine.webp' },
    shortDescription: 'Machine for removing husks from coconuts.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-05',
    name: 'Husk Chipping Machine',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/husk-chipping-machine.webp' },
    shortDescription: 'Chips coconut husks into smaller pieces.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-06',
    name: 'Horizontal Pith Briqurtting Machine',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/horizontal-pith-briquetting-machine.webp' },
    shortDescription: 'Horizontal machine for briquetting pith.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-07',
    name: '1.5 HP Willowing Machine',
    productType: 'machine',
    category: 'Willowing',
    image: { id: '/machinery/1.5hp-willowing-machine.webp' },
    shortDescription: '1.5 HP machine for willowing coir fibers.',
    specifications: [{ key: 'Power', value: '1.5 HP' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-08',
    name: 'Double Head Spooling Machine',
    productType: 'machine',
    category: 'Spooling',
    image: { id: '/machinery/spooling-machine.webp' },
    shortDescription: 'Spooling machine with double heads for increased efficiency.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-09',
    name: 'Single Head Spooling Machine',
    productType: 'machine',
    category: 'Spooling',
    image: { id: '/machinery/single-head-spooling-machine.webp' },
    shortDescription: 'Single head spooling machine.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-10',
    name: 'Automatic Loom',
    productType: 'machine',
    category: 'Weaving',
    image: { id: '/machinery/automatic-loom.webp' },
    shortDescription: 'Fully automatic loom for coir weaving.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-11',
    name: 'Semi Automatic Loom',
    productType: 'machine',
    category: 'Weaving',
    image: { id: '/machinery/semi-automatic-loom.webp' },
    shortDescription: 'Semi-automatic loom for coir weaving.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-12',
    name: 'Manual Hand Loom',
    productType: 'machine',
    category: 'Weaving',
    image: { id: '/machinery/manual-hand-loom.webp' },
    shortDescription: 'Traditional manual hand loom.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-13',
    name: 'Electronic Ratt',
    productType: 'machine',
    category: 'Spinning',
    image: { id: '/machinery/electronic-ratt.webp' },
    shortDescription: 'Electronic ratt for spinning coir yarn.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-14',
    name: 'Hydraulic Bailing Press',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/hydraulic-bailing-press.webp' },
    shortDescription: 'Hydraulic press for bailing coir products.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-15',
    name: 'Pith Briqurtting Machine',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/pith-briqurtting-machine.webp' },
    shortDescription: 'Machine for making pith briquettes.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-16',
    name: 'Garden Article Press',
    productType: 'machine',
    category: 'Processing',
    image: { id: '/machinery/garden-article-press.webp' },
    shortDescription: 'Press machine for manufacturing garden articles.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-17',
    name: '5 HP UNBUNDLING AND WILLOWING MACHINE',
    productType: 'machine',
    category: 'Willowing',
    image: { id: '/machinery/5hp-unbundling-and-willowing-machine.webp' },
    shortDescription: 'Combined unbundling and willowing machine with 5 HP motor.',
    specifications: [{ key: 'Power', value: '5 HP' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-18',
    name: 'Winding Machine',
    productType: 'machine',
    category: 'Winding',
    image: { id: '/machinery/winding-machine.webp' },
    shortDescription: 'Machine for winding coir yarn.',
    specifications: [],
    brochureUrl: '#',
  },
  {
    id: 'mach-19',
    name: '0.5 HP Willowing Machine',
    productType: 'machine',
    category: 'Willowing',
    image: { id: '/machinery/0.5hp-willowing-machine.webp' },
    shortDescription: 'Compact 0.5 HP willowing machine.',
    specifications: [{ key: 'Power', value: '0.5 HP' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-20',
    name: 'Willowing Machine 5HP',
    productType: 'machine',
    category: 'Willowing',
    image: { id: '/machinery/willowing-machine-5HP.webp' },
    shortDescription: 'Heavy-duty 5 HP willowing machine.',
    specifications: [{ key: 'Power', value: '5 HP' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-21',
    name: 'Willowing Machine 5 HP motor Pin Type (Mulluthangi)',
    productType: 'machine',
    category: 'Willowing',
    image: { id: '/machinery/willowing-machine-5hp-motor-in-type-mulluthangi.webp' },
    shortDescription: 'Pin type (Mulluthangi) willowing machine with 5 HP motor.',
    specifications: [{ key: 'Power', value: '5 HP' }, { key: 'Type', value: 'Pin Type' }],
    brochureUrl: '#',
  },
  {
    id: 'mach-22',
    name: 'Integrated Defibering Unit',
    productType: 'machine',
    category: 'Defibering',
    image: { id: '/machinery/integrated-defibering-unit.webp' },
    shortDescription: 'Complete integrated unit for defibering.',
    specifications: [],
    brochureUrl: '#',
  },
];

const tenders: Tender[] = [
  {
    id: 'ten-001',
    title: 'Supply of Raw Steel Materials',
    referenceNumber: 'KSCMMC/PROC/2024/018',
    closingDate: '2024-08-15',
    documentUrl: '/tenders/tender-001.pdf',
  },
  {
    id: 'ten-002',
    title: 'Annual Maintenance Contract for CNC Machines',
    referenceNumber: 'KSCMMC/AMC/2024/003',
    closingDate: '2024-08-22',
    documentUrl: '/tenders/tender-002.pdf',
  },
  {
    id: 'ten-003',
    title: 'Procurement of Electrical Components',
    referenceNumber: 'KSCMMC/ELEC/2024/011',
    closingDate: '2024-09-01',
    documentUrl: '/tenders/tender-003.pdf',
  },
];

const jobs: Job[] = [
  {
    id: 'job-01',
    title: 'Manager',
    location: 'Alappuzha, Kerala',
    department: 'Contract Basis',
    description: [
      'Qualification: MBA/B.Tech (Mech)',
      'Experience: 5 years in manufacturing sector',
      'Preference will be given in Machinery manufacturing',
      'Age: Below 40 years',
      'Salary: Rs.30,000/-',
    ],
  },
  {
    id: 'job-02',
    title: 'Asst. Manager',
    location: 'Alappuzha, Kerala',
    department: 'Contract Basis',
    description: [
      'Qualification: MBA/B.Tech (Mech)',
      'Experience: 2 years in Marketing sector',
      'Preference will be given in Machinery and products marketing',
      'Age: Below 35 years',
      'Salary: Rs.28,000/-',
    ],
  },
  {
    id: 'job-03',
    title: 'Officer (HR)',
    location: 'Alappuzha, Kerala',
    department: 'Contract Basis',
    description: [
      'Qualification: MBA(HRM)',
      'Experience: 2 years in HR Department',
      'Preference will be given in Manufacturing sector',
      'Age: Below 35 years',
      'Salary: Rs.25,000/-',
    ],
  },
];

const news: NewsArticle[] = [
  {
    id: 'news-01',
    title: 'KSCMMC partners with German firm for tech upgrade',
    date: '2024-07-20',
    summary: 'A new partnership aims to bring cutting-edge automation to our spinning machinery line.',
    image: { id: 'news-1' },
    link: '#',
  },
  {
    id: 'news-02',
    title: 'Innovation in Geotextiles: New loom unveiled',
    date: '2024-07-15',
    summary: 'Our R&D department has successfully developed a wider and faster loom for coir geotextiles.',
    image: { id: 'news-2' },
    link: '#',
  },
  {
    id: 'news-03',
    title: 'KSCMMC wins award at International Coir Fair',
    date: '2024-06-28',
    summary: 'Recognized for "Best Innovation in Coir Machinery" at the annual global event.',
    image: { id: 'news-3' },
    link: '#',
  },
];


export const getProducts = () => products;
export const getProductById = (id: string) => products.find(p => p.id === id);

export const getTenders = () => tenders;

export const getJobs = () => jobs;

export const getNews = () => news;
