import { FaqForm } from '@/components/forms/faq-form';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faLightbulb } from '@fortawesome/free-solid-svg-icons';

export default function FaqPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 md:px-6 pt-4 pb-12 md:py-12">
      <div className="text-center">
        <div className="inline-flex items-center justify-center rounded-full bg-primary/10 p-3">
            <FontAwesomeIcon icon={faLightbulb} className="h-8 w-8 text-primary" />
        </div>
        <h1 className="font-headline mt-4 text-2xl md:text-4xl font-bold">AI-Powered FAQ</h1>
        <p className="mx-auto mt-4 max-w-2xl text-base md:text-lg text-muted-foreground">
          Have a question about KSCMMC, our products, or services? Ask our AI assistant for a quick answer.
        </p>
      </div>
      
      <div className="mt-12">
        <FaqForm />
      </div>

       <div className="mt-12 rounded-lg border bg-card p-6 text-center">
        <h3 className="font-semibold">Disclaimer</h3>
        <p className="mt-2 text-sm text-muted-foreground">
          The answers are generated by an AI and may not always be 100% accurate. For official information, please refer to the respective pages or contact us directly.
        </p>
      </div>
    </div>
  );
}
